--Table Counts
SELECT 'COUNTRIES' AS TABEL_NAME,    (SELECT COUNT(*) FROM COUNTRIES) AS ROW_COUNT FROM dual UNION
SELECT 'LOCATIONS',    (SELECT COUNT(*) FROM LOCATIONS) FROM dual UNION
SELECT 'ZIPCODES',    (SELECT COUNT(*) FROM ZIPCODES) FROM dual UNION
SELECT 'HALLS',  (SELECT COUNT(*) FROM HALLS) AS TABLE_COUNT FROM dual UNION
SELECT 'MOVIES',    (SELECT COUNT(*) FROM MOVIES) FROM dual UNION
SELECT 'PERFORMANCES',    (SELECT COUNT(*) FROM PERFORMANCES) FROM dual UNION
SELECT 'THEATHERS',    (SELECT COUNT(*) FROM THEATHERS) FROM dual UNION
SELECT 'TICKETS',    (SELECT COUNT(*) FROM TICKETS) FROM dual UNION
SELECT 'VIEWERS',    (SELECT COUNT(*) FROM VIEWERS) FROM dual
;


--Many to many relation (movies & halls)
---
SELECT m.TITLE, m.RELEASE_DATE, m.RUNTIME, p.STARTTIME, p.ENDTIME, h.FLOOR, h.SCREENTYPE
FROM MOVIES m
         JOIN PERFORMANCES p ON m.MOVIE_ID = p.MOVIE_ID
         JOIN HALLS h ON p.HALL_ID = h.HALL_ID;

--2 deep relation (viewers - tickets - performances)
---
SELECT v.FIRSTNAME,v.LASTNAME, t.PRICE, p.STARTTIME, p.ENDTIME, h.FLOOR, h.SCREENTYPE
FROM VIEWERS v
         JOIN TICKETS t ON v.VIEWER_ID = t.VIEWER_ID
         JOIN PERFORMANCES p ON t.PERFORMANCE_ID = p.PERFORMANCE_ID
         JOIN HALLS h ON p.HALL_ID = h.HALL_ID;

--Viewer location
---
SELECT v.FIRSTNAME,v.LASTNAME, l.STREET, l.HOUSENUMBER, z.ZIPCODE, z.CITY, c.COUNTRY
FROM VIEWERS v
         JOIN LOCATIONS l ON v.LOCATION_ID = l.LOCATION_ID
         JOIN ZIPCODES z ON l.COUNTRYCODE = z.COUNTRYCODE AND l.ZIPCODE = z.ZIPCODE
         JOIN COUNTRIES c ON z.COUNTRYCODE = c.COUNTRYCODE;

--Theather location
---
SELECT t.NAME,t.PHONENUMBER, l.STREET, l.HOUSENUMBER, z.ZIPCODE, z.CITY, c.COUNTRY
FROM THEATHERS t
         JOIN LOCATIONS l ON t.LOCATION_ID = l.LOCATION_ID
         JOIN ZIPCODES z ON l.COUNTRYCODE = z.COUNTRYCODE AND l.ZIPCODE = z.ZIPCODE
         JOIN COUNTRIES c ON z.COUNTRYCODE = c.COUNTRYCODE;


-- Bewijs phonenumber theather (+x)
INSERT INTO THEATHERS (NAME, SHOP, PHONENUMBER, LOCATION_ID)
VALUES ('Bewijs Cinema', 0, '3225147498',1);

-- Bewijs runtime movie (20<->250 min)
INSERT INTO MOVIES (TITLE, RELEASE_DATE, GENRE, TYPE, RUNTIME, PLOT, LANGUAGE)
VALUES ('Bewijs Movie', TO_DATE('2000-01-01', 'yyyy-mm-dd'), 'Action', 'Movie', 350,
        'Bewijs plot',
        'EN');

-- Bewijs gender viewer (M, V or X)
INSERT INTO VIEWERS (FIRSTNAME, LASTNAME, BIRTHDATE, GENDER, EMAIL, LOCATION_ID)
VALUES ('Bewijs', 'Naam', TO_DATE('2000-01-01', 'yyyy-mm-dd'), 'Y', 'bewijs.naam@gmail.com',1);