-- In dit bestand zet je je package specificatie. Hier komen alle specificaties van je publieke functies.
CREATE
    OR REPLACE PACKAGE PKG_MOVIES IS

    PROCEDURE EMPTY_TABLES;
-- Add procedures
    PROCEDURE ADD_MOVIE(TITLE IN VARCHAR2, RELEASE_DATE IN DATE, GENRE IN VARCHAR2, "TYPE" IN VARCHAR2,
                        RUNTIME IN NUMBER, PLOT IN VARCHAR2, LANGUAGE IN VARCHAR2);
    PROCEDURE ADD_VIEWER(FIRSTNAME IN VARCHAR2, LASTNAME IN VARCHAR2, BIRTHDATE IN DATE, GENDER IN VARCHAR2,
                         EMAIL IN VARCHAR2, STREET IN VARCHAR2, HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2,
                         COUNTRYCODE IN VARCHAR2);
    PROCEDURE ADD_THEATHER(NAME IN VARCHAR2, SHOP IN NUMBER, PHONENUMBER IN VARCHAR2, STREET IN VARCHAR2,
                           HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2, COUNTRYCODE IN VARCHAR2);
    PROCEDURE ADD_HALL(SEAT_AMOUNT IN NUMBER, FLOOR IN NUMBER, HALLNUMBER IN NUMBER, SCREENTYPE IN VARCHAR2,
                       THEATHERNAME IN VARCHAR2, STREET IN VARCHAR2, HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2,
                       COUNTRYCODE IN VARCHAR2);
    PROCEDURE ADD_PERFORMANCE(MOVIE_TITLE IN VARCHAR2, THEATHERNAME IN VARCHAR2, STREET IN VARCHAR2,
                              HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2, COUNTRYCODE IN VARCHAR2, FLOOR IN NUMBER,
                              HALLNUMBER IN NUMBER, STARTTIME IN DATE);
    PROCEDURE ADD_TICKET(EMAIL IN VARCHAR2, MOVIE_TITLE IN VARCHAR2, THEATHERNAME IN VARCHAR2, STREET IN VARCHAR2,
                         HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2, COUNTRYCODE IN VARCHAR2, FLOOR IN NUMBER,
                         HALLNUMBER IN NUMBER, STARTTIME IN DATE, SEATNUMBER IN NUMBER, PRICE IN NUMBER);
    PROCEDURE ADD_LOCATION(STREET IN VARCHAR2, HOUSENUMBER IN NUMBER, ZIPCODE IN VARCHAR2, COUNTRYCODE IN VARCHAR2);
    PROCEDURE ADD_ZIPCODE(CITY IN VARCHAR2, ZIPCODE IN VARCHAR2, COUNTRYCODE IN VARCHAR2);
    PROCEDURE ADD_COUNTRY(COUNTRYCODE IN VARCHAR2, COUNTRY IN VARCHAR2);

END;