-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-17 16:33:47 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE countries CASCADE CONSTRAINTS;

DROP TABLE halls CASCADE CONSTRAINTS;

DROP TABLE locations CASCADE CONSTRAINTS;

DROP TABLE movies CASCADE CONSTRAINTS;

DROP TABLE performances CASCADE CONSTRAINTS;

DROP TABLE theathers CASCADE CONSTRAINTS;

DROP TABLE tickets CASCADE CONSTRAINTS;

DROP TABLE viewers CASCADE CONSTRAINTS;

DROP TABLE zipcodes CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE countries (
    countrycode INTEGER NOT NULL,
    country     VARCHAR2(100)
);

ALTER TABLE countries ADD CONSTRAINT countries_pk PRIMARY KEY ( countrycode );

CREATE TABLE halls (
    hall_id     INTEGER NOT NULL,
    seat_amount INTEGER,
    floor       INTEGER,
    screentype  VARCHAR2(25 CHAR),
    theather_id INTEGER NOT NULL
);

ALTER TABLE halls ADD CONSTRAINT hall_pk PRIMARY KEY ( hall_id );

CREATE TABLE locations (
    location_id INTEGER NOT NULL,
    street      VARCHAR2(100 CHAR),
    "number"    INTEGER,
    countrycode INTEGER NOT NULL,
    zipcode     VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE locations ADD CONSTRAINT locations_pk PRIMARY KEY ( location_id );

CREATE TABLE movies (
    movie_id     INTEGER NOT NULL,
    title        VARCHAR2(20 CHAR),
    release_date DATE,
    genre        VARCHAR2(20 CHAR),
    type         VARCHAR2(20 CHAR),
    runtime      INTEGER,
    plot         VARCHAR2(150 CHAR),
    language     VARCHAR2(20)
);

ALTER TABLE movies ADD CONSTRAINT movie_pk PRIMARY KEY ( movie_id );

CREATE TABLE performances (
    performance_id INTEGER NOT NULL,
    movie_id       INTEGER NOT NULL,
    hall_id        INTEGER NOT NULL,
    starttime      DATE NOT NULL
);

ALTER TABLE performances ADD CONSTRAINT relation_3_pk PRIMARY KEY ( performance_id );

CREATE TABLE theathers (
    theather_id INTEGER NOT NULL,
    name        VARCHAR2(25 CHAR),
    shop        SMALLINT,
    phonenumber VARCHAR2(10 CHAR),
    location_id INTEGER NOT NULL
);

ALTER TABLE theathers ADD CONSTRAINT theathers_ck_phonenumber CHECK ( phonenumber LIKE '+%_' );

ALTER TABLE theathers ADD CONSTRAINT theather_pk PRIMARY KEY ( theather_id );

CREATE TABLE tickets (
    viewer_id      INTEGER NOT NULL,
    performance_id INTEGER NOT NULL,
    price          NUMBER
);

ALTER TABLE tickets ADD CONSTRAINT relation_1_pk PRIMARY KEY ( viewer_id,
                                                               performance_id );

CREATE TABLE viewers (
    viewer_id   INTEGER NOT NULL,
    firstname   VARCHAR2(20 CHAR),
    lastname    VARCHAR2(20 CHAR),
    birthdate   DATE,
    email       VARCHAR2(100 CHAR),
    location_id INTEGER NOT NULL
);

ALTER TABLE viewers ADD CONSTRAINT reviewer_ck_email CHECK ( email LIKE '%_@__%.__%' );

ALTER TABLE viewers
    ADD CONSTRAINT viewers_ck_birthday CHECK ( birthday < now() );


ALTER TABLE Viewers 
    ADD CONSTRAINT Viewers_CK_gender
check(gender LIKE 'M' OR 'V' OR 'X');

ALTER TABLE viewers ADD CONSTRAINT viewer_pk PRIMARY KEY ( viewer_id );

CREATE TABLE zipcodes (
    city        VARCHAR2(100 CHAR),
    zipcode     VARCHAR2(4 CHAR) NOT NULL,
    countrycode INTEGER NOT NULL
);

ALTER TABLE zipcodes ADD CONSTRAINT zipcodes_pk PRIMARY KEY ( zipcode,
                                                              countrycode );

ALTER TABLE halls
    ADD CONSTRAINT fk_hall_theather FOREIGN KEY ( theather_id )
        REFERENCES theathers ( theather_id );

ALTER TABLE locations
    ADD CONSTRAINT fk_location_zipcode FOREIGN KEY ( zipcode,
                                                     countrycode )
        REFERENCES zipcodes ( zipcode,
                              countrycode );

ALTER TABLE performances
    ADD CONSTRAINT fk_performance_hall FOREIGN KEY ( hall_id )
        REFERENCES halls ( hall_id );

ALTER TABLE performances
    ADD CONSTRAINT fk_performance_movie FOREIGN KEY ( movie_id )
        REFERENCES movies ( movie_id );

ALTER TABLE theathers
    ADD CONSTRAINT fk_theather_location FOREIGN KEY ( location_id )
        REFERENCES locations ( location_id );

ALTER TABLE tickets
    ADD CONSTRAINT fk_ticket_performance FOREIGN KEY ( performance_id )
        REFERENCES performances ( performance_id );

ALTER TABLE tickets
    ADD CONSTRAINT fk_ticket_viewer FOREIGN KEY ( viewer_id )
        REFERENCES viewers ( viewer_id );

ALTER TABLE viewers
    ADD CONSTRAINT fk_viewer_location FOREIGN KEY ( location_id )
        REFERENCES locations ( location_id );

ALTER TABLE zipcodes
    ADD CONSTRAINT fk_zipcodes_countrie FOREIGN KEY ( countrycode )
        REFERENCES countries ( countrycode );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
